import type { Issue, Review } from './schema';

const BOT_MARKER = '<!-- manavarya-bot-review -->';

export function renderMarkdown(
  prNumber: number,
  review: Review,
  risk: number,
  quality: number,
  model: string
): string {
  const { summary, issues, notes } = review;
  const critical = issues.filter((i) => i.severity === 'CRITICAL');
  const warnings = issues.filter((i) => i.severity === 'WARNING');
  const suggestions = issues.filter((i) => i.severity === 'SUGGESTION');

  const lines: string[] = [];
  lines.push(BOT_MARKER);
  lines.push(`# PR #${prNumber} — Code Audit Report`);
  lines.push('');
  lines.push('## Summary');
  lines.push(`- Files changed: **${summary.files_changed}**`);
  lines.push(`- Lines added: **${summary.lines_added}**`);
  lines.push(`- Lines removed: **${summary.lines_removed}**`);
  if (summary.main_concern) {
    lines.push(`- Main concern: ${summary.main_concern}`);
  }
  lines.push('');

  lines.push(`## Scores`);
  lines.push(`- Risk: **${risk}/10**`);
  lines.push(`- Quality: **${quality}/100**`);
  lines.push('');

  if (issues.length === 0) {
    lines.push('No high-confidence issues detected.');
    lines.push('');
  } else {
    if (critical.length) {
      lines.push('## Critical');
      critical.forEach((i) => lines.push(renderIssue(i)));
      lines.push('');
    }
    if (warnings.length) {
      lines.push('## Warnings');
      warnings.forEach((i) => lines.push(renderIssue(i)));
      lines.push('');
    }
    if (suggestions.length) {
      lines.push('## Suggestions');
      suggestions.forEach((i) => lines.push(renderIssue(i)));
      lines.push('');
    }
  }

  if (notes.length) {
    lines.push('## Notes');
    notes.forEach((n) => lines.push(`- ${n}`));
    lines.push('');
  }

  lines.push('---');
  lines.push(
    `_Generated by [manavarya-bot](https://github.com/bot-manavarya/reviewer) using \`${model}\`._`
  );

  return lines.join('\n');
}

function renderIssue(i: Issue): string {
  const loc = i.line > 0 ? `\`${i.file}:${i.line}\`` : `\`${i.file}\``;
  return [
    `- **${loc}** — ${i.issue}`,
    `  - **Why:** ${i.why}`,
    `  - **Fix:** ${i.fix}`,
    `  - _confidence: ${i.confidence.toFixed(2)}_`,
  ].join('\n');
}

export { BOT_MARKER };

export function renderFailureMarkdown(
  prNumber: number,
  stage: string,
  errMsg: string,
  model: string,
  provider: string
): string {
  const hint = diagnose(errMsg);
  const clipped = errMsg.length > 1200 ? errMsg.slice(0, 1200) + '…' : errMsg;
  const lines = [
    BOT_MARKER,
    `# PR #${prNumber} — Review Failed`,
    '',
    `The reviewer couldn't complete its audit for this pull request.`,
    '',
    '## Failure',
    `- **Stage:** ${stage}`,
    `- **Provider:** \`${provider}\``,
    `- **Model:** \`${model}\``,
    '',
    '## Error',
    '```',
    clipped,
    '```',
  ];
  if (hint) {
    lines.push('', '## Suggested fix', '', hint);
  }
  lines.push(
    '',
    '_This comment will be replaced with the real audit on the next successful run — push any new commit to retry._',
    '',
    '---',
    `_Generated by [manavarya-bot](https://github.com/bot-manavarya/reviewer)._`
  );
  return lines.join('\n');
}

function diagnose(msg: string): string | null {
  const m = msg.toLowerCase();
  if (m.includes('rate limited locally')) {
    return [
      'The daily review quota for this repo has been hit (configurable via `max-daily-reviews`).',
      '',
      'Pushing another commit before the quota resets (UTC midnight) will be skipped.',
    ].join('\n');
  }
  if (m.includes('429') || m.includes('quota')) {
    return [
      'Gemini free tier quota is exhausted or not enabled for this API key.',
      '',
      '- Check usage at https://aistudio.google.com/apikey',
      '- Try a different model by editing `model:` in `.github/workflows/manavarya-bot.yml`',
      '- Or enable billing on the Google Cloud project tied to the API key',
    ].join('\n');
  }
  if (m.includes('401') || m.includes('unauthorized')) {
    return [
      'The `GEMINI_API_KEY` secret is missing or invalid.',
      '',
      '- Reissue at https://aistudio.google.com/apikey',
      '- Update the repo secret under Settings → Secrets and variables → Actions',
    ].join('\n');
  }
  if (m.includes('json')) {
    return 'The model returned non-JSON. Try a more capable model (e.g. `gemini-1.5-pro`) or retry.';
  }
  if (m.includes('403') && m.includes('accessible by personal access token')) {
    return 'The `MANAVARYA_BOT_TOKEN` secret needs more scope. Use a classic PAT with `repo` + `workflow` scopes.';
  }
  return null;
}
